### ISSUE TITLE
Change the name of the destination file ?

### ISSUE THREAD

**Issue by mickey** [nathancolgate/s3-swf-upload-plugin#1]
First, KUDOS for this fork, really amazing !

I got a question, is there a way to change the name of the destination file (on s3) ?
Thanks,

**Comment by nathancolgate** [comment]
Thanks, Mickey.

As it stands, you can't SET the name of the destination file before it is uploaded to S3.  You can set the prefix, though.  Currently all the file name stuff is handled by the original (and awesomely untouched) elctech code.  It seems that it has been doing it's job really well for a long time.

You can CHANGE the name via the application using any S3 library after it's been uploaded, though.  Use the onUploadComplete callback to make an AJAX call to the app and pass along the file's current key (path and filename).

Good luck!

**Comment by mickey** [comment]
Thanks Nathan,

I finally made a fork with the ability to change the destination path : http://github.com/mickey/s3-swf-upload-plugin

**Comment by nathancolgate** [comment]
Mickey, Just a heads up, I had to re-write some stuff to get it to work in 10.1
