### ISSUE TITLE
Cant se files

### ISSUE THREAD

**Issue by maxgronlund** [nathancolgate/s3-swf-upload-plugin#10]
Hi Nethan, I followed your tutorial to the letter, 
please have a look at: http://furious-ocean-71.heroku.com/ as you can se there is no graphics for the files? I got the same issue on local host.

I'm running rails 3.0.0.
ruby 1.9.2 on localhost and 1.8.7 on heroku.

files are uploading OK from Heroku but not from localhost?

**Comment by maxgronlund** [comment]
I have uploaded the project to http://sysx.dk/sites/default/files/swfuploader.zip
Best regards Max

**Comment by maxgronlund** [comment]
PS you rocks

**Comment by nathancolgate** [comment]
Please see nutheory's fix in Issue #9 for handling strings in ruby 1.9.2

**Comment by maxgronlund** [comment]
That worked, thanks :-)

**Comment by maxgronlund** [comment]
Graphics still not updating, please have a look at http://electric-beach-80.heroku.com/. I have the same issue on localhost, i followed the GREAT guide, and did the entire demo project over again followed  http://vimeo.com/11363680 
Still no graphics! any idear? what I'm doing wrong, do I have to have the YUI library installed  ?

**Comment by nathancolgate** [comment]
You are using the old queue.source instead of queue.files java script (see the release notes).  My bad though, I hadn't updated the JS gist.  Fixed though. Thanks for the heads up.

**Comment by maxgronlund** [comment]
Working perfect! thanks for your quick response
