### ISSUE TITLE
How to integrate with Paperclip [Solution]

### ISSUE THREAD

**Issue by nathancolgate** [nathancolgate/s3-swf-upload-plugin#12]
I've gotten a handful of folks asking how this works with something like PaperClip.  Here's a starting point:

http://gist.github.com/575842

Good luck!

-Nathan

**Comment by kunanyi** [comment]
Wow. Just a note to say thankyou. This is a really nicely thought out gem.

**Comment by nathancolgate** [comment]
There are still a few 'enhancements' that would be nice to work out, but thanks for taking the time to leave a comment! -N
