### ISSUE TITLE
Question: Possible to change destination name entirely?

### ISSUE THREAD

**Issue by JohnPostlethwait** [nathancolgate/s3-swf-upload-plugin#13]
Currently when the S3 upload finished, regardless of the keyPrefix you give it, it will tack the original file name on to the end of this keyPrefix. Is it at all possible to write an entirely new name for the s3 destination?

**Comment by nathancolgate** [comment]
Yes, but this would be outside the scope of this upload tool.  To accomplish it, you can pass the keyPrefix and filename to the server and let it do whatever you want to the file (rename, relocate, copy, resize, compress, etc...).  An example using paperclip is outlined in this gist:

http://gist.github.com/575842

**Comment by JohnPostlethwait** [comment]
Thanks for the quick response and example!
