### ISSUE TITLE
Feature request: fileDialogComplete support

### ISSUE THREAD

**Issue by jeppeliisberg** [nathancolgate/s3-swf-upload-plugin#15]
I ask for support for a callback upon file dialog closure, similar to
http://demo.swfupload.org/Documentation/#fileDialogComplete

Hope this is possible?

**Comment by yuvaltobias** [comment]
I second that request.

**Comment by monicao** [comment]
+1

**Comment by nathancolgate** [comment]
Closing based on lack of demand.
