### ISSUE TITLE
Flash show error after files selected

### ISSUE THREAD

**Issue by phuong-nguyen** [nathancolgate/s3-swf-upload-plugin#16]
This is a urgent error to me. After I select file from the flash dialog, error will be shown. I have uploaded a movie describe the error here: http://ec2-67-202-32-137.compute-1.amazonaws.com/s3_upload_plugin_error.mov

I'm running Flash 10.1.53.64

Other user running Flash 10.0.x.x seems to be fine.

**Comment by nathancolgate** [comment]
It looks like you're running some kind of debugger version of Flash. This page recommends updating to a higher version than you currently have:

http://www.adobe.com/support/flashplayer/downloads.html
