### ISSUE TITLE
Question marks "?" and forward slashes "/" completely change file names

### ISSUE THREAD

**Issue by abelmartin** [nathancolgate/s3-swf-upload-plugin#19]
Hi Nathan,

First, allow me to say how much I love this uploader!

Second, I've noticed that files with question marks in their titles "image?.jpg" strip everything after the question mark, including the mark itself.  In addition, anything with with a forward slash "image/.jpg" in the title strips everything before the forward slash, including the forward slash itself.

The issue is that the name is also changed in the javascript array of files so I can't access the original name for some post processing after the upload occurs.

Is there some way via Javascript to relax the way this is being interpreted?
If not, would you mind pointing out in the code where you're stripping this out and how I can recompile the swf?

Thanks,
-a

**Comment by nathancolgate** [comment]
Hey Abel,

Oof. No idea what's going on there. I'm a ruby guy in a flex mask for this project, so I'm not sure where to start. But I'll keep this issue open and see if any else chimes in.

Re: recompiling: I just followed some step-by-step article to get the flex SDK working on my machine.

-Nate

**Comment by abelmartin** [comment]
Hi Nate,

Thanks for the quick reply.  Users will have to get a warning message near the top of the upload page until I can figure this thing out :).
