### ISSUE TITLE
Exceptions raised inside methods called by ExternalInterface don't bubble into JS

### ISSUE THREAD

**Issue by ncr** [nathancolgate/s3-swf-upload-plugin#2]
When I have buggy code inside callbacks called by ExternalInterface, I never get any exceptions thrown in JS and all debugging gets really hard. I think it is because the AS code doesn't "marshalExceptions".

Please take a look at http://www.adobe.com/livedocs/flash/9.0/ActionScriptLangRefV3/flash/external/ExternalInterface.html#marshallExceptions and http://code.google.com/p/swfupload/issues/detail?id=153

P.S. This is probably the real reason (bugs in handlers but no feedback) I couldn't get this plugin working before.

Thanks,

Jacek

**Comment by nathancolgate** [comment]
I tried playing around with MarshalledExceptions but without any luck. I've fixed some issues with Flash Player 10.1, so hopefully you can get it to work!

**Comment by ncr** [comment]
For the exceptions - I just wrap all callbacks that will be called from flash in try/catch and log errors myself. Seems to be working fine.
