### ISSUE TITLE
error with rails generate......

### ISSUE THREAD

**Issue by jasonkemm** [nathancolgate/s3-swf-upload-plugin#20]
Nathan -- I am following the tutorial, have made it to step 3, "rails generate....." here is the error that I am getting:
# rails generate s3_swf_upload:uploader

Usage:
  rails new APP_PATH [options]

Options:
  -O, [--skip-active-record]  # Skip Active Record files
      [--dev]                 # Setup the application with Gemfile pointing to your Rails checkout
  -d, [--database=DATABASE]   # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db)
                              # Default: sqlite3
  -J, [--skip-prototype]      # Skip Prototype files
  -T, [--skip-test-unit]      # Skip Test::Unit files
  -m, [--template=TEMPLATE]   # Path to an application template (can be a filesystem path or URL)
  -G, [--skip-git]            # Skip Git ignores and keeps
  -b, [--builder=BUILDER]     # Path to an application builder (can be a filesystem path or URL)
      [--edge]                # Setup the application with Gemfile pointing to Rails repository
      [--skip-gemfile]        # Don't create a Gemfile
  -r, [--ruby=PATH]           # Path to the Ruby binary of your choice
                              # Default: /usr/local/bin/ruby

Runtime options:
  -s, [--skip]     # Skip files that already exist
  -f, [--force]    # Overwrite files that already exist
  -p, [--pretend]  # Run but do not make any changes
  -q, [--quiet]    # Supress status output

Rails options:
  -v, [--version]  # Show Rails version number and quit
  -h, [--help]     # Show this help message and quit

Description:
    The 'rails new' command creates a new Rails application with a default
    directory structure and configuration at the path you specify.

Example:
    rails new ~/Code/Ruby/weblog

```
This generates a skeletal Rails installation in ~/Code/Ruby/weblog.
See the README in the newly created application to get going.
```

rails version: 
# rails -v

Rails 3.0.1

Any ideas? This is an established app, just trying to update the uploader to something a little more useful :)

Thank you!
Jason

**Comment by nathancolgate** [comment]
You should be able to run 'rails generate' from the command line without any problem.  It is how you would generate other things like models, migrations, scaffolds, etc...

If you can't get past it, follow the instructions for pre rails 3 installation.

**Comment by jasonkemm** [comment]
Thanks, tried installing manually per the instructions, copied all files into their locations, added the require view_helpers,  and I cannot get it running this way. 

I see the uploader on my uploading page, but when I select a file, it is not added to the que. & when clicking the "start uploading" (using the complex example) I get an error referencing the ".../s3_uploads.xml..." not being found.

Any ideas?

Thank you, 
Jason
