### ISSUE TITLE
problem got sigioerror

### ISSUE THREAD

**Issue by thesetu** [nathancolgate/s3-swf-upload-plugin#23]
i did everything like you said now i dont get it why it isn't working i did everything i could but couldn't get my git repository for this try is in https://github.com/thesetu/swftestthesetu plz help me on this

**Comment by philipkd** [comment]
You might need to make the fix mentioned here:
https://github.com/nathancolgate/s3-swf-upload-plugin/issues#issue/9

**Comment by nathancolgate** [comment]
@thesetu, @philipkd is spot on. Not sure how this issue lingered for a year. Closing. Thanks, @philipkd
