### ISSUE TITLE
Unidentifiable Upload Error

### ISSUE THREAD

**Issue by dankozlowski** [nathancolgate/s3-swf-upload-plugin#27]
I followed the installation directions, but I get an error in my browser saying "There was an error" and the following stuff in my server console: (Rails 3.0.3, Ruby 1.9.2.)

Started GET "/s3_uploads.xml?key=apAsm%2Epng&content%5Ftype=image%2Fpng" for 127.0.0.1 at 2011-01-06 21:41:32 -0800
  Processing by S3UploadsController#index as XML
  Parameters: {"key"=>"apAsm.png", "content_type"=>"image/png"}
Completed 200 OK in 5ms (Views: 3.3ms | ActiveRecord: 0.0ms)

Thanks!

**Comment by krzkrzkrz** [comment]
I am coming across the same issue. Not much I can do since the error message is pretty vague. Anyone know what is going on?

Same environment, Rails 3.0.3 and Ruby 1.9.2

**Comment by krzkrzkrz** [comment]
Ahhhh, looks like my crossdomain.xml was missing on my bucket. Works now
