### ISSUE TITLE
'File not found in the queue'

### ISSUE THREAD

**Issue by glennr** [nathancolgate/s3-swf-upload-plugin#28]
Configured app as per instructions, including;

  :onFileNotInQueue => "alert('File not found in the queue');",
1. Click browse
2. Add files
3. Click 'delete' on one of the files in the list.
4. See popup alert 'File not found in the queue' (but file is removed from the list OK).

Problem also exists on demo app:  http://s3swfuploader.heroku.com/

**Comment by gmgreg** [comment]
+1  I'm seeing the same thing.

**Comment by psykidellic** [comment]
+1, seeing the same thing. For production - I have disabled the alert. I dont have Flex knowledge but if you can point me out to the right code, I would be more than willing to fix it.

**Comment by nathancolgate** [comment]
Flash just isn't a thing anymore. Calling this closed!
