### ISSUE TITLE
Error using the generator

### ISSUE THREAD

**Issue by tamoyal** [nathancolgate/s3-swf-upload-plugin#3]
<code>
admins-MacBook-Pro-2:fsg_distro tamoyal$ rails generate s3_swf_upload:uploader
/Users/tamoyal/.bundle/ruby/1.8/bundler/gems/s3-swf-upload-plugin-92ef46f0f8ea2918b3c41518bda8964dcdc26b78-master/lib/s3_swf_upload/s3_config.rb:14:in `load_config': You have a nil object when you didn't expect it! (NoMethodError)
You might have expected an instance of Array.
The error occurred while evaluating nil.[]
    from /Users/tamoyal/.bundle/ruby/1.8/bundler/gems/s3-swf-upload-plugin-92ef46f0f8ea2918b3c41518bda8964dcdc26b78-master/lib/s3_swf_upload/railtie.rb:8
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/initializable.rb:25:in`instance_exec'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/initializable.rb:25:in `run'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/initializable.rb:55:in`run_initializers'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/initializable.rb:54:in `each'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/initializable.rb:54:in`run_initializers'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/application.rb:119:in `initialize!'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/application.rb:81:in`send'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/application.rb:81:in `method_missing'
    from /Users/tamoyal/Projects/fsg_distro/config/environment.rb:5
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/application.rb:94:in`require'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/application.rb:94:in `require_environment!'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/application.rb:81:in`send'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/application.rb:81:in `method_missing'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/commands.rb:16
    from script/rails:6:in`require'
    from script/rails:6
</code>

**Comment by tamoyal** [comment]
one more thing:
<code>
admins-MacBook-Pro-2:fsg_distro tamoyal$ rails -v
Rails 3.0.0.beta4
</code>

**Comment by nathancolgate** [comment]
I tried making the rescue statement more liberal.  Not sure why the generator is calling the initializer.  Maybe something new in beta4 that takes a second looking at.

http://github.com/nathancolgate/s3-swf-upload-plugin/commit/7238f16137bab55301d069d2655a04f5dcce71d0

**Comment by tamoyal** [comment]
I had an amazon s3 config file already created.  Moving it out of the app fixed the issue.  Maybe your code saw it was there but didn't validate it had the necessary attributes not to crash....or the specific crash wasn't caught.  You can probably repro by putting a bad amazon config.

**Comment by nathancolgate** [comment]
Try this:

http://github.com/nathancolgate/s3-swf-upload-plugin/commit/1f3646441602a4fb0ba19d93abcf8ec6131d97bb

**Comment by tamoyal** [comment]
I'm not sure off-hand how to try that particular commit.  I tried putting this in my Gemfile:
<code>
gem 's3_swf_upload', :git => 'http://github.com/nathancolgate/s3-swf-upload-plugin/commit/1f3646441602a4fb0ba19d93abcf8ec6131d97bb'
</code>
but the bundle failed.

**Comment by nathancolgate** [comment]
Try:
- Re-running bundle install
- Remove the directory (below) and re run bundler

/Users/tamoyal/.bundle/ruby/1.8/bundler/gems/s3-swf-upload-plugin-92ef46f0f8ea2918b3c41518bda8964dcdc26b78-master

**Comment by tamoyal** [comment]
First thing I get is this:
<code>
admins-MacBook-Pro-2:fsg_distro tamoyal$ bundle installFetching http://github.com/nathancolgate/s3-swf-upload-plugin/commit/1f3646441602a4fb0ba19d93abcf8ec6131d97bb
error: inflate: data stream error (incorrect header check)
error: inflate: data stream error (incorrect header check)
error: inflate: data stream error (incorrect header check)
error: inflate: data stream error (incorrect header check)
error: File 0000000000000000000000000000000000000000 (http://github.com/nathancolgate/s3-swf-upload-plugin/commit/1f3646441602a4fb0ba19d93abcf8ec6131d97bb/objects/00/00000000000000000000000000000000000000) corrupt
Getting pack list for http://github.com/nathancolgate/s3-swf-upload-plugin/commit/1f3646441602a4fb0ba19d93abcf8ec6131d97bb
Getting alternates list for http://github.
</code>
It must be expecting a different file type

**Comment by tamoyal** [comment]
btw, I know how to get around this issue so I am only doing this stuff to help your code.  if you don't care about this particular case, you may just want to make it a known issue.  if you do care, i am happy to continue helping

**Comment by nathancolgate** [comment]
Weird stuff.  Thanks for the help.  I'm not too worried now, so I'll just leave this open so other folks can see it.
