### ISSUE TITLE
Not working: Getting a "No method error"

### ISSUE THREAD

**Issue by AndreaBarbon** [nathancolgate/s3-swf-upload-plugin#36]
Following your video on Vimeo, with the simplest configuration i get this error on my rails server:

```
NoMethodError (undefined method `&' for "v":String): app/controllers/s3_uploads_controller.rb:36:in `index'
```

And the line 36 in s3_uploads_controller.rb is the following:

```
signature = b64_hmac_sha1(secret_key, policy)
```

Please can you help me?

EDIT: Here's my Development.log file

NoMethodError (undefined method `&' for "v":String):
  app/controllers/s3_uploads_controller.rb:36:in`index'

Rendered /Users/abramo/.rvm/gems/ruby-1.9.2-p180/gems/actionpack-3.0.7/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.2ms)
Rendered /Users/abramo/.rvm/gems/ruby-1.9.2-p180/gems/actionpack-3.0.7/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (35.3ms)
Rendered /Users/abramo/.rvm/gems/ruby-1.9.2-p180/gems/actionpack-3.0.7/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (42.9ms)

**Comment by nathancolgate** [comment]
Please see this issue:

https://github.com/nathancolgate/s3-swf-upload-plugin/issues/9
