### ISSUE TITLE
Uploads bigger than 2GB

### ISSUE THREAD

**Issue by muanis** [nathancolgate/s3-swf-upload-plugin#38]
Does it support uploads bigger than 2GB? From my tests, it just hangs. I've read something related to flash limits on upload sizes.

**Comment by nathancolgate** [comment]
I don't think so, no.

**Comment by mischa78** [comment]
So, what is the limit? 2GB?

**Comment by nathancolgate** [comment]
I don't know off the top of my head, but you might want to look at the file-transfer-in limits for S3.

**Comment by muanis** [comment]
I've tested with 1.99 works. 2GB doesn't.

I couldn't find anything on limits on amazon side. There's a 5GB limit for individual buckets.

**Comment by mischa78** [comment]
Thanks!

**Comment by heizusan** [comment]
Sorry for the zombie post - but this hang is exactly what I experienced, as well - also, I'm using a version of the uploader that may be out of date...

A little poking around in javascript showed at least _some_ behavior around a 2 GB limit: When uploading a file that the filesystem reported as 2.9 Gb, the file size reported on the way into the uploader was 2971580103 - actually about 2.75 Gb. But who's counting.

The uploader hung for _ever_, and when progress events finally came back (I only got 2, and then it hung _again_), they reported a total byte count of 2147483647 - _precisely_ 2 Gb, and only about 28k uploaded. Now, in a 32 bit system, an unsigned integer (what should be used for something like file size) is limited at 4 Gb. But a _signed_ integer would be limited to 2 Gb. Perhaps there's a problem around the bit depth of flash?

**Comment by nathancolgate** [comment]
Looks like chunking is the only current work-around:

http://stackoverflow.com/questions/2923766/flash-uploader-that-can-handle-2gb-files
http://swfupload.org/forum/generaldiscussion/584

Looks like other tools have gotten it to work suing Flash's urlstream mode (chunking enabled):

http://www.plupload.com/punbb/viewtopic.php?id=995

You would have to do some vodoo to get S3 to put the chunks back together.

Hope that helps!

**Comment by nathancolgate** [comment]
Oof. Maybe not:

http://www.cabo.dk/blog/jakobs-blog/survey-of-large-browser-uploads

**Comment by heizusan** [comment]
Looks like S3 already supports Multi-part/chunked uploading. It's just a matter of implementing it, client side. ;)

http://docs.amazonwebservices.com/AmazonS3/latest/dev/uploadobjusingmpu.html?r=7748

**Comment by nathancolgate** [comment]
Yeah. And according to that cabo.dk site above Flash, HTML5 + JS and Silverlight do not support client-side chunking.  Only Java does. :(

**Comment by heizusan** [comment]
I think flash does support chunking - and streaming - uploads. But it may still be limited by the 2 Gb issue on where it can chunk from/to. :\

HTML5 doesn't support _streaming_ uploads. But it does support chunking. It's more a question of browser support, at this point.

**Comment by heizusan** [comment]
That article is also now about 8 months out of date. HTML5 is moving at a decent clip in its changes.
