### ISSUE TITLE
signatureIOError "Error #2032" on Firefox 3.6 using Windows Vista

### ISSUE THREAD

**Issue by JohnPostlethwait** [nathancolgate/s3-swf-upload-plugin#39]
This only happens on this configuration of browsers while attempting to upload any video file to S3. From my research this is a Flash error that results from a bunch of different things such as cross-domain permissions, wrong file paths, etc. I cannot, however, find any of these issues with our application as this same script works just fine using any other browser/OS combo (even Firefox 3.6 on other OS')

Any insights into this, why this might happen, or anything else? I've been playing with this for hours now and just can't find anything useful...

**Comment by nathancolgate** [comment]
Sorry, John. This sounds like a browser issue, not a plugin issue.  We're a mac shop, too, so I haven't had any insight into Windows since XP. :) Good luck though, and if you find any solutions, post 'em here!
