### ISSUE TITLE
Generator tells me to run the generator

### ISSUE THREAD

**Issue by devth** [nathancolgate/s3-swf-upload-plugin#4]
```
% rails generate s3_swf_uploader:uploader
% WARNING: You are using the S3 SWF Uploader gem, which wants a config file at /../config/amazon_s3.yml, but none could be found. You should try running 'rails generate s3_swf_upload:uploader'
```

Infinite loop of WARNINGS!

**Comment by devth** [comment]
typo!

should be `rails generate s3_swf_upload:uploader`

**Comment by nathancolgate** [comment]
"Infinite loop of WARNINGS!" - Sounds like my junior high experience.

Someone else reported a similar error.  Seems to be due to rails 3 moving up to beta4.  Just to confirm, are you on beta4?

**Comment by devth** [comment]
Yeah beta4. I think my typo caused the problem. I ran the generator after creating the config manually and it worked.

**Comment by kerrizor** [comment]
I managed to get the same warning, but it seems to have run successfully
