### ISSUE TITLE
Where to find "non-rails" version?

### ISSUE THREAD

**Issue by andrewhavens** [nathancolgate/s3-swf-upload-plugin#40]
I use Rails on my personal projects (which is how I found out about this library). But now I need to integrate something like this in my PHP application. Is there a "standalone" version of this library that I can use in my PHP application?

**Comment by nathancolgate** [comment]
Not that I'm aware of. However, almost the entire library can stand on it's own. The javascript, html and swf files will work regardless of server technology.  The only thing that you'd need to convert to PHP is the controller action:

https://github.com/nathancolgate/s3-swf-upload-plugin/blob/master/lib/s3_swf_upload/railties/generators/uploader/templates/s3_uploads_controller.rb

The first thing that popped up on Google for me was:

http://undesigned.org.za/2007/10/22/amazon-s3-php-class

Hopefully that would be enough to get you going!

**Comment by nathancolgate** [comment]
Another good find:

http://www.uploadify.com/forums/discussion/1416/uploading-to-amazon-s3/p1
