### ISSUE TITLE
IE Loading Issues

### ISSUE THREAD

**Issue by taybenlor** [nathancolgate/s3-swf-upload-plugin#44]
We seem to be running into issues with the button loading on IE, perhaps related to: https://github.com/GreenAsJade/s3-swf-upload-plugin/issues/4 in the original repo.

**Comment by taybenlor** [comment]
I tried updating SWFObject to v2.2 and that seems to have done the trick, as advised in #14

> Nevermind. I solved it by upgrading the embedded SWFObject v2.1 to v2.2.

Have pushed it up to https://github.com/taybenlor/s3-swf-upload-plugin will submit pull request now.

**Comment by andrewhavens** [comment]
Since SWFObject 2.2 has already been merged...can't this issue be closed now?

**Comment by taybenlor** [comment]
Probably.
