### ISSUE TITLE
Ie8 / windows xp

### ISSUE THREAD

**Issue by mickey** [nathancolgate/s3-swf-upload-plugin#5]
Hi Nathan,
It looks like there's some bugs on windows XP with IE8 or IE7.
The browse button appears but selecting a file doesn't trigger the "onFileAdd" or "onQueueChange" events. 
I thought first it was caused by me but it appears than the demo at s3swfupload.heroku.com doesn't work.
I'm trying to find out why now but if you got an idea ...
I'll let you know if I find something,

Thanks.

**Comment by nathancolgate** [comment]
Should be fixed. Check out my comments in the other closed issues.
