### ISSUE TITLE
Feature Request: Final File Name Configuration & keyPrefix

### ISSUE THREAD

**Issue by JohnPostlethwait** [nathancolgate/s3-swf-upload-plugin#51]
I have a case where I HAVE to have the final file name on S3 be a very specific name/format. We are using a version of this code from well over a year ago and the file name on S3 ends up just being the keyPrefix we set during initialization, however; after updating this code couple of days ago we noticed that the file name is now our keyPrefix PLUS the original file name appended to the end. For us this is not something that can be as we have a service that looks for a very specific file name format for our uploads.

I see in S3Signature.as, over a year ago, this snippet of code was touched:

``` actionscript
  upload_options.key              = prefixPath + upload_options.FileName;
```

I am not positive this causes this issue, as I am not too familiar with this code, but it was my best find... Would it be possible to add an initialization option to NOT append the original file name to the end of the final file name?

I assume the version we were previously using, which made the keyPrefix the ENTIRE filename, was deemed to be a bug and changed to this, but we rely on it.

I also see that there is a part of the README now that tells people to do this with the back-end after the upload is complete, but that is super asynchronous, and somewhat kludgy as it can seemingly be done right from this bundle of code... (And, is being done already when the file is created on S3.)

Thanks!

-John

**Comment by nathancolgate** [comment]
Hey John,

Presently, my extent of maintaining this code is managing pull requests.  Feel free to fork the gem, add the functionality that you need (without removing the above functionality), and I'll be happy to roll it in.

-N

**Comment by JohnPostlethwait** [comment]
Oh, ok, cool, good to know, thanks!

**Comment by TheCorp** [comment]
Any chance I could get the non-minified version of the main s3_upload.js file? I am thinking about making this change and it would help with working on this. Thanks!

**Comment by nathancolgate** [comment]
This?

https://github.com/nathancolgate/s3-swf-upload-plugin/blob/master/lib/s3_swf_upload/railties/generators/uploader/templates/s3_upload.js

**Comment by TheCorp** [comment]
Ah sorry I should have been more clear, I assume to get any of this file 
prefixing stuff done I would need to play around with line 4 which seems 
minified or condensed? Maybe I am confused about where some of the work 
is getting done for the file name itself.

I know from one of the other issues (#65) that I might be able to hack 
it into the flex file here:
flex_src/src/com/nathancolgate/s3_swf_upload/S3Signature.as

Not sure though. Thanks for the quick response!

**Comment by nathancolgate** [comment]
Line 4 of s3_upload.js is SWFObject v2.2 (see comment in lines 1-3). You should be able to get a non-minified version at the project page (http://code.google.com/p/swfobject/), but I think it would be unwise to tinker with it.

It has been renamed to avoid any potential conflicts (i.e. in case someone is using a different version of SWFObject)

**Comment by TheCorp** [comment]
Gotcha, ok ill dig into the code more then and let you know if I get something built. Thanks again for the info.
