### ISSUE TITLE
Trigger the "browse files" button using Javascript?

### ISSUE THREAD

**Issue by 238357** [nathancolgate/s3-swf-upload-plugin#53]
Hi, I would like to integrate the plugin with my existing Javascript code, how can I force Javascript to click on the "browse files" button? Should I use Flux's ExternalInterface class? Which function should I look into?

Thank you!

**Comment by nathancolgate** [comment]
A (legitimate) security feature in Flash does not allow the browse button to be called by JavaScript.  Please see the "Known Issues" section of the README.
