### ISSUE TITLE
Rails 3.1.3  ActionView::Template::Error (s3_upload.js isn't precompiled):

### ISSUE THREAD

**Issue by hamzashahid** [nathancolgate/s3-swf-upload-plugin#57]
I am using Rails 3.1.3 and the plugin loads into a component on page upon an ajax call. It runs fine on my local machine. However when I deploy it on heroku it crashes giving this error. I would be grateful for any kind of help. Thanks !

**Comment by nathancolgate** [comment]
This is part of rails 3.1+

Add the js file to your production.rb file. Look for the precompile line.
