### ISSUE TITLE
Cancel ongoing upload?

### ISSUE THREAD

**Issue by gangsteryepyedye** [nathancolgate/s3-swf-upload-plugin#59]
Hello,

 Is there a way to cancel an ongoing upload? I used "s3_swf_1_object.removeFileFromQueue" but it didn't seem to work.

Thanks

**Comment by nathancolgate** [comment]
Something other than 'stopUploading'?

**Comment by gangsteryepyedye** [comment]
Yea, I was looking for something can stop a single file upload progress. But it seems the library only provides 'stopUploading', which stops the entire process.

**Comment by nathancolgate** [comment]
Closing as I do not believe this is possible.
