### ISSUE TITLE
Does this work with self-signed certificates?

### ISSUE THREAD

**Issue by andrewhavens** [nathancolgate/s3-swf-upload-plugin#61]
I've really been pulling my hair out over this one. I have a fork of this project that I've been using successfully for a while. Now I'm trying to integrate it into a project that is secure over HTTPS, but I'm getting errors which lead me to believe it's a problem with Flash trying to fetch the signature XML over HTTPS. The `onSignatureIOError` function is getting called with an `io_error_event.text` of `Error #2032`. Is it a known issue that the SWF has problems with self-signed certificates? Or could it be something I'm not even thinking of?

**Comment by nathancolgate** [comment]
Epic question. I have no idea.
