### ISSUE TITLE
Drag & Drop (HTML5)

### ISSUE THREAD

**Issue by scanferla** [nathancolgate/s3-swf-upload-plugin#64]
I've just tested the gem and it worked great! The best solution I've found to upload directly to s3 using Rails and getting all the cool things such as upload progress, etc...

Is it possible to make a drag & drop work? Would JavaScript be able to tell Flash what file to upload? I guess this would be the flow as the file would be dropped into an HTML zone.

Anyway, I think we would have problems with Flash Security, right?

Thanks!

**Comment by nathancolgate** [comment]
@scanferla I'm unaware of any drag-and-drop functionality within flash. if that changes, let's open this back up.

**Comment by pablofierro** [comment]
Hello, I was looking at the Dropbox web app source code and they are using swfupload and drag & drop support, any ideas on how they are doing this ?

Is there any way to manually pass a file to swfupload ?
