### ISSUE TITLE
this.obj().startUploading is not a function http://localhost:3000/javascripts/s3_upload.js?1329378949 Line 80

### ISSUE THREAD

**Issue by k6s3** [nathancolgate/s3-swf-upload-plugin#68]
Hello,

This is a weird one. The upload doesn't start but firebug doesn't show any JS errors.

However, when I try to execute "s3_swf_1_object.startUploading();" in the firebug console, I get the below error -
this.obj().startUploading is not a function http://localhost:3000/javascripts/s3_upload.js?1329378949 Line 80

This seemed to be working fine in a previous commit but is now broken.
I have not made any significant changes to this part of the code.

Been trying to figure which change broke this for the past 2 days, but I don't seem to be getting anywhere!

Any help would be highly appreciated..

**Comment by k6s3** [comment]
PS: When i mentioned 'working in a previous commit', i'm referring to my application's code, not the plugin's code. 

Surprisingly, the uploader continues to work with IE!! This error seems to be occurring for FF and Chrome.

**Comment by nathancolgate** [comment]
Any luck with this issue? Can you share any code in a Gist?
