### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by omarvelous** [nathancolgate/s3-swf-upload-plugin#7]
Not sure if it is both of my setups, mac and pc.... but All of a sudden, my s3-swf stopped working... I checked your demo... it deosn't appear to be working either... Is this just me?

**Comment by nathancolgate** [comment]
The demo is working fine for me.  Strange flash version maybe?

**Comment by omarvelous** [comment]
I thought so... Let me check that out... Ohhh flash...
