### ISSUE TITLE
Feature Request: Chunking Large Files

### ISSUE THREAD

**Issue by nathancolgate** [nathancolgate/s3-swf-upload-plugin#70]
Depending on your system, Flash can not handle files larger than 2GB: http://stackoverflow.com/questions/4240196/upload-file-using-flash-uploaders-what-is-size-limit

They must be chunked.  This seems possible. Other uploaders are doing it. For example Plupload: http://www.plupload.com

But getting Plupload to work with S3 and your application doesn't seem to be an option: http://www.plupload.com/punbb/viewtopic.php?id=578

If anyone would like to take a look at Plupload (https://github.com/moxiecode/plupload) and see what they're doing to chunk files via flash, it would be a welcome addition to the plugin.

**Comment by dlegr250** [comment]
@nathancolgate I've been looking into your plugin and it looks really good.  However, the particular use case I'm working on involves loading extremely large files directly to S3 (something up to 30GB files).  Has any progress been made on getting flash to chunk files larger than 2GB?  Unfortunately I'm not a flash developer at all so I'm unable to examine Plupload and see what they're doing with regards to flash chunking.

**Comment by nathancolgate** [comment]
@dlegr250 Afraid not. I'm not a flash guy either... hence the open request. Hoping someone will come along with the right skillset!

**Comment by mbhanushali** [comment]
really need this feature. I hope someone with knowledge of flash can help!

**Comment by wsl** [comment]
Maybe this one is an option? https://github.com/cinely/mule-uploader
It's the html part only, straight to S3, so you will have to implement your own backend calls

**Comment by nathancolgate** [comment]
Flash just isn't a thing anymore. Calling this closed!
