### ISSUE TITLE
Firefox 13.0.1 (Windows definitely, untested in OS X), Flash 11.3, simple upload button doesn't work.

### ISSUE THREAD

**Issue by heizusan** [nathancolgate/s3-swf-upload-plugin#71]
Pretty much what the title says.

We have the newest version of the .swf file installed. It displays a single "upload" button, and the rest of our interface is html that updates based on js events from the uploader.

It works fine in all browsers, even with the newest version of flash.

Except for Firefox 13.0.1, with the newest version of Flash 11.3 (released on June 8th) - in windows for sure, but currently untested in Mac OS X. In this environment, clicking the upload button fails to bring up the file selection dialog.

**Comment by nathancolgate** [comment]
Wish I had a more informative response, but that browser / flash combo looks like it is causing lots of folks trouble:

http://support.mozilla.org/en-US/questions/930736

If you can pinpoint it to this plugin, we can open this back up. But for now I'm going to treat this as a browser issue, and close this issue.
