### ISSUE TITLE
Support Storage Class option for S3 storage.

### ISSUE THREAD

**Issue by jkillian** [nathancolgate/s3-swf-upload-plugin#73]
Basically, this gem should have an option so files being uploaded to S3 can be marked to be stored in the cheaper, reduced redundancy storage. This setting could be server-side or client-side, as it does not appear to be part of the policy file hash.

Relevant: http://docs.amazonwebservices.com/AmazonS3/latest/API/RESTObjectPOST.html

**Comment by nathancolgate** [comment]
Closing based on lack of demand.
