### ISSUE TITLE
Browse button is invisble

### ISSUE THREAD

**Issue by nzifnab** [nathancolgate/s3-swf-upload-plugin#77]
We've started serving our static assets from Amazon S3 in addition to putting document uploads there.  I'm having an issue where when I set the :swfFilePath, :buttonUpPath, :buttonOverPath, and :buttonDownPath parameters in `s3_swf_upload_tag()` I am not getting a 'browse' button for file selection. Everything works when I set these paths to a locally stored swf/images, but when I point them to our publically-viewable assets on S3 they show up blank.

I've set a cross-origin request policy (CORS) on the S3 assets bucket, and it is properly allowing the fonts to be loaded from S3 on the site so this doesn't appear to be the issue.

Any idea why I wouldn't be seeing a 'Browse' button?

Edit:  I also added a crossdomain.xml to my assets bucket (in addition to the working one that I have on the document uploads bucket):

```
<?xml version="1.0"?>
<!DOCTYPE cross-domain-policy SYSTEM "http://www.macromedia.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
    <allow-access-from domain="*" secure="true"/>
</cross-domain-policy>
```

but that didn't fix anything either.

**Comment by wildebeast** [comment]
I'm also experiencing this issue.

**Comment by wildebeast** [comment]
I think I was experiencing the problem because I was trying to load the swf and the button images from another domain (via cloudfront).  After forcing them to load from my domain, it worked again.

**Comment by nathancolgate** [comment]
Thanks for the workaround, @wildebeast
