### ISSUE TITLE
Demo site not working?

### ISSUE THREAD

**Issue by kerrizor** [nathancolgate/s3-swf-upload-plugin#8]
Clicking on the "Browse" button brings up a file selection dialog box, and clicking "Start Uploading" makes the call to get the credentials, but no other traffic is occuring, nor any ui elements updating or otherwise indicating there's a transfer taking place.  I had a packet tracer handy, and watched for traffic between my machine and.. well, anywhere meaningful.. and didn't see a single bit move around.

(osx10.5, FF, Chrome, and Safari, multiple machines, Flash 10.1)

I dunno, I thought maybe it was just something wrong in the demo, so I went step-for-step through the docs and the Vimeo vid (great to see that, BTW) and had the same exact behavior - credentials requested but no transfer.  I reproduced this on team-mates laptop (10.6 etc etc) 

Am I missing something? :(

**Comment by martinhuard** [comment]
Works great here with Flash 10.0.45.2 in Firefox, but not with Chome and Flash 10.1.53.64.

I have the exact same problem as described here.

When I updated Firefox with Flash 10.1.53.64, it stoppend working.

Any workaround other than rolling back Flash version?

Thanks.

**Comment by omarvelous** [comment]
Yup, I just came back to tell my findings as well... Does not work with the latest 10.1 versions of Flash.

**Comment by omarvelous** [comment]
Any update or fix?

**Comment by dan-79** [comment]
Seeing similar with 10.1.  Any update other than rolling back flash?

**Comment by omarvelous** [comment]
Unless someone knows Flash, we are a duck in water. Nate said he is very backed up, and won't have time until Sept to look into this... Wish I knew flash! I'm sure the error is prob so minor as to break from v9 to v10.1.

**Comment by nathancolgate** [comment]
Good news. Wrapped up some stuff early and was able to tackle this tonight.  The deal: Flash Player 10.1 did not allow ExternalInterface to pass a FileReference object to Javascript. So I added a toJavascript function that converts FileReference into simple Objects.  You pretty much get the same attributes (name, size, type). Hopefully this will survive any future releases!

If you get a chance, update to 0.3.0 and give it a test (I'll update the demo site later this weekend) and if you like it, buy me a beer (which actually means: help me pad my entertainment budget so I can take my wife out to dinner and help validate the hours spent working on this stuff)

**Comment by omarvelous** [comment]
You the man! I got you on some brew!
