### ISSUE TITLE
Flash cookies bug

### ISSUE THREAD

**Issue by chrisdpeters** [nathancolgate/s3-swf-upload-plugin#81]
I've noticed specifically with Firefox on Windows that this plugin will not work when sessions are required in order to perform the upload (due to being blocked by authentication logic or whatever). In my app, I get a 406 Not Acceptable error when I try to use the SWF to upload a file to S3. This is because Flash does not read the browser's cookies and thus doesn't post any.

This gem could possibly provide a solution to the problem:
https://github.com/trevorturk/flash_cookie_session

The problem is that I can't tell exactly where to patch in the cookie key and forgery protection token when Flash tries to `POST` to the server. It appears that these values would need to be set in the JavaScript produced in order for Flash to pick them up and `POST` them along with the request for the S3 signature.

Unfortunately, I know little about Flex (nor have the desire to know anything about it ;)), so I won't be able to contribute a solution. But I figured having an issue here to outline the problem may help someone else to come up with a good solution in a Pull Request. Or perhaps there was something that I was missing?

**Comment by nathancolgate** [comment]
Closing this as it could be stale. Feel free to re-open if it is still an problem.
