### ISSUE TITLE
Repackage and release updated gem (Rails >= 3.1 changes not in release gem)

### ISSUE THREAD

**Issue by schmielson** [nathancolgate/s3-swf-upload-plugin#83]
I noticed that the gemspec hasn't been updated in about a year. Recent changes, such as that which only includes the s3_upload.js file if the Rails version is < 3.1, are actually quite useful. 
Would love it if the live gem included those commits. Thank you!

**Comment by nathancolgate** [comment]
Flash just isn't a thing anymore. Calling this closed!
