### ISSUE TITLE
video duration validation

### ISSUE THREAD

**Issue by daniramdani** [nathancolgate/s3-swf-upload-plugin#84]
is there any validation to check the duration for video file ?

thanks

**Comment by nathancolgate** [comment]
No.

**Comment by daniramdani** [comment]
Hi nathan, tnx for reply, can I get the return of success upload from s3 (s3_upload_controller), cuz I need do another action after upload success. thanks

**Comment by nathancolgate** [comment]
Yeah. Check out the onUploadFinish callback.

**Comment by daniramdani** [comment]
ohh yaa,  nathancolgate, thank u so much, this gem is very usefull for me, thanks bro, GBU
