### ISSUE TITLE
PC users are able to sneak in file types not listed in the fileTypes parameter

### ISSUE THREAD

**Issue by jensneeoosh** [nathancolgate/s3-swf-upload-plugin#86]
hi nathan, 

the plugin works on mac, but on pc, users are able to type in a file type that is not listed and able to select anything. have you heard of this problem before? 

thanks!
jenni

**Comment by nathancolgate** [comment]
I haven't heard of this. But it would be a flash issue, so it is probably documented out there somewhere.

**Comment by schmielson** [comment]
As far as I can tell, this is a bug with Chrome on Windows XP. 

I've verified that the file type restriction is honored for the following:

Mac: Chrome, Firefox, and Safari (all latest browser versions)
Windows 7: IE 8, IE 9, IE 10

As a workaround I suggest registering for the "queueChange" event (set when calling `s3_swf_upload_tag`) and then within your handler checking the filename of the file that was just added to make sure that it has the expected extension.

**Comment by jensneeoosh** [comment]
sounds like a good idea, thanks @schmielson!

**Comment by schmielson** [comment]
@jmchng10 sure, no problem!

**Comment by nathancolgate** [comment]
Thanks for the workaround, @schmielson
